theme: jekyll-theme-cayman
title: Welcome to Sequana home page
description: a set of NGS pipelines (sequence analysis)


# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Post: "post"


