title: Welcome to Sequana home page
description: a set of NGS pipelines (sequence analysis)
theme: jekyll-theme-cayman
show_downloads: false

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Post: "post"


